### ISSUE TITLE
Unable to install SyMPC on raspberry pi 4b

### ISSUE THREAD

**Issue by stevenjgore** [OpenMined/SyMPC#286] opened 2021-07-29 00:42 UTC
## Question
**Describe your question in ONE SENTENCE.**

I am unable to install SyMPC on my raspberry pi 4b that I'm using for research even though I've successfully installed the dependancies.

## Further Information
Describe your question in greater length here.

I followed the install instructions and was able to successfully install PySyft, PyTorch, Torchvision, and the dependancies for SyMPC, but I get an install error when trying to run pip install .

I also tried running "pip install -e ." per the solution for issue #265 , but it still did not work for me and it gave me the same error message.

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Ubuntu
 - OS Version: 21.04
 - Language Version: Python 3.9.5
 - Package Manager Version: APT

## Additional Context

I am trying to install this on a raspberry pi4 and I'm not sure if SyMPC can install/run on an ARM architecture.

**Comment by stevenjgore** [comment] 2021-07-29 13:45
I was able to solve the install issue, but now when I i try to import Session from sympc.session, I get the following error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_2327/3063307635.py in <module>
      4 import torch
      5 
----> 6 from sympc.session import Session
      7 from sympc.session import SessionManager
      8 from sympc.tensor import MPCTensor

/usr/lib/python3.9/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.9/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.9/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.9/importlib/_bootstrap.py in _load_backward_compatible(spec)

/usr/local/lib/python3.9/dist-packages/wrapt/importer.py in load_module(self, fullname)
    154 
    155     def load_module(self, fullname):
--> 156         module = self.loader.load_module(fullname)
    157         notify_module_loaded(module)
    158 

/usr/local/lib/python3.9/dist-packages/sympc/__init__.py in <module>
      9 from pkg_resources import get_distribution
     10 
---> 11 from . import api  # noqa: 401
     12 from . import approximations  # noqa: 401
     13 from . import config  # noqa: 401

/usr/local/lib/python3.9/dist-packages/sympc/api.py in <module>
     21 import sympc
     22 
---> 23 from . import protocol  # noqa: 401
     24 from . import session  # noqa: 401
     25 from . import store  # noqa: 401

/usr/local/lib/python3.9/dist-packages/sympc/protocol/__init__.py in <module>
      4 from .aby3 import ABY3
      5 from .falcon import Falcon
----> 6 from .fss import FSS
      7 from .protocol import Protocol
      8 

/usr/local/lib/python3.9/dist-packages/sympc/protocol/fss/__init__.py in <module>
      1 """FSS Protocol."""
      2 
----> 3 from .fss import FSS
      4 
      5 __all__ = ["FSS"]

/usr/local/lib/python3.9/dist-packages/sympc/protocol/fss/fss.py in <module>
     16 # third party
     17 import numpy as np
---> 18 import sycret
     19 import torch as th
     20 import torchcsprng as csprng  # type: ignore

/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/__init__.py in <module>
----> 1 from sycret.fss import EqFactory  # noqa: 401
      2 from sycret.fss import LeFactory  # noqa: 401

/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/fss.py in <module>
      2 import numpy as np
      3 
----> 4 from .sycret import lib
      5 from .utils import _as_i64_array
      6 from .utils import _as_u8_array

/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/__init__.py in <module>
      4 from .ffi import ffi
      5 
----> 6 lib = ffi.dlopen(os.path.join(os.path.dirname(__file__), 'native.so'), 4098)
      7 del os

OSError: cannot load library '/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/native.so': /usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/native.so: cannot open shared object file: No such file or directory

**Comment by rasswanth-s** [comment] 2021-07-29 13:48
Could you install the dependencies and check in the root folder by
`pip install -r requirements.dev.txt`

**Comment by stevenjgore** [comment] 2021-07-29 13:56
hi @rasswanth-s . thanks for the quick reply.

during the install process, i successfully installed the dependencies by running "pip install -r requirements.dev.txt". when I look in the directory listed in error message, the "/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/" directory is there, but the "native.so" file is not.

is there somewhere else I should be looking?

**Comment by rasswanth-s** [comment] 2021-07-29 14:08
After installing the dependencies , you are getting the same error?

**Comment by stevenjgore** [comment] 2021-07-29 17:15
@rasswanth-s, sorry, I misread you're original post. I had previously run just requirements.txt.

I have now run "pip install -r requirements.dev.txt" and it looks like it successfully installed those new dependencies, but i am still getting the same error when trying to import Session from sympc.session.

OSError: cannot load library '/usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/native.so': /usr/local/lib/python3.9/dist-packages/sycret-0.1.3-py3.9.egg/sycret/sycret/native.so: cannot open shared object file: No such file or directory

**Comment by rasswanth-s** [comment] 2021-07-30 00:35
@tholop  , @arturomf94  could you take a look at this error?

**Comment by arturomf94** [comment] 2021-07-30 00:44
Yes - I'm trying to replicate a build with Raspberry Pi 4 atm. Will get back to you as soon as I've got more info.

**Comment by stevenjgore** [comment] 2021-07-30 00:48
thanks for the help. on a separate install on my VM with x86 architecture, i have the native.so file. would a possible solution be to manually move the native.so file to the directory on the raspberry pi?

**Comment by arturomf94** [comment] 2021-07-30 01:02
The problem evidently comes from `sycret`. My best guess (maybe @tholop can confirm) is that we need to re-build `sycret` with `Maturin` for this architecture? In order to do that, I've installed `Maturin` and tried to run it, with something like this: 

```
cd ~ && git clone https://github.com/OpenMined/sycret.git
cd sycret
wget -c https://github.com/PyO3/maturin/releases/download/v0.11.2/maturin-aarch64-unknown-linux-musl.tar.gz
tar xvzf maturin-aarch64-unknown-linux-musl.tar.gz
python3 -m venv venv && source venv/bin/activate
./maturin develop -b cffi --release
```
If you want to replicate this you'll need to install Rust. 

However, I'm getting errors in the compilation. I'm still trying to figure out how (if possible) they can be solved.

**Comment by arturomf94** [comment] 2021-07-30 01:03
Cross-compilation might help, so if the compilation doesn't work on the RPi I'll try to do that.

**Comment by arturomf94** [comment] 2021-07-30 21:05
@stevenjgore - Unfortunately, I think it won't be possible to install/use SyMPC on a Raspberry Pi at the moment. The reason for this is that, even if we try to compile `sycret` on the Raspberry Pi, the problem is that one of the crates used, [aesni](https://docs.rs/aesni/0.10.0/aesni/), uses "special Intel instructions to run AES faster on the CPU" (as pointed out by @tholop).

We will try to make this an optional dependency. We've created [this issue](https://github.com/OpenMined/sycret/issues/24) for that.

**Comment by arturomf94** [comment] 2021-10-14 00:25
@stevenjgore - `sycret` now has successful builds for `aarch` architectures, so you should have no problem with runnning this on a RPi now. I'll close this, but if you have any questions or comments, don't hesitate to reach out! :+1:

**Closed by arturomf94** 2021-10-14 00:25 UTC
