### ISSUE TITLE
Change nr_parties from protobuff to int32

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/SyMPC#105] opened 2021-03-31 08:10 UTC
## Description
For the moment, the `nr_parties` field from the `Session` is set to `bytes` and we should set it to `int32` to properly indicate that we expect a number and not something else

The protobuf file can be found [here](https://github.com/OpenMined/PySyft/blob/dev/proto/lib/sympc/session.proto).
The person taking this issue should also change how serialization/deserialization is done for the `nr_parties` class.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
- The protobuf files should also be compiled using `protoc`

**Comment by hershd23** [comment] 2021-07-17 17:35
Is this issue still available? Willing to take it up

**Comment by kamathhrishi** [comment] 2021-07-18 11:47
@hershd23 Hey the issue is still open. 
https://github.com/OpenMined/PySyft/blob/dev/packages/syft/proto/lib/sympc/session.proto

**Comment by hershd23** [comment] 2021-07-18 12:10
A couple of questions

In @gmuraru's comment
"For the moment, the nr_parties field from the Session is set to bytes and we should set it to int32 to properly indicate that we expect a number and not something else"
I guess this would only require me to set the type of `nr_parties` to int32 in `session.proto` linked above. That would mean, I'll add a pull request to pysyft right?

"The person taking this issue should also change how serialization/deserialization is done for the nr_parties class."
Where is this serialization/deserialzation code written can you point out the file to me?

**Comment by kamathhrishi** [comment] 2021-07-18 14:09
@hershd23 You can find it here https://github.com/OpenMined/PySyft/tree/dev/packages/syft/src/syft/lib/sympc

**Comment by hershd23** [comment] 2021-07-18 15:13
Got it.

This means the only changes will be in Pysyft and I should submit a PR there. The sessions class in SyMPC already takes `nr_parties` as int type.

In the serialization and deserialization functions located [here](https://github.com/OpenMined/PySyft/blob/dev/packages/syft/src/syft/lib/sympc/session_util.py) `rank` which is already of type `int32` can be directly fed to the constructor of `MPCSession_PB` and can be read from it directly. So the change to serialization and deserialization of `nr_parties` would only mean removing the bytes->int conversion logic right?

**Comment by kamathhrishi** [comment] 2021-07-19 03:43
You are right. You should fork PySyft dev branch and work on it. When you make changes to .proto files you can rebuild it using the command `PySyft/packages/syft/scripts/build_proto.sh` , which should be called from syft folder. 

In order to test changes run, unit tests in PySyft/packages/syft/tests/syft/lib/sympc/ with your fork of PySyft. Another thing to test is to run some SyMPC unit tests, but by installing your fork of PySyft.

**Comment by kamathhrishi** [comment] 2021-07-19 03:45
_In the serialization and deserialization functions located here rank which is already of type int32 can be directly fed to the constructor of MPCSession_PB and can be read from it directly. So the change to serialization and deserialization of nr_parties would only mean removing the bytes->int conversion logic right?_ , Right

**Comment by hershd23** [comment] 2021-07-19 18:16
PR which solves this issue https://github.com/OpenMined/PySyft/pull/5804

**Closed** 2021-07-20 17:12 UTC
Labels: good first issue
